name: GCC Linux Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TYPE: [Debug] 

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install libgl-dev 
           
    - name: Python setup
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.0'
        architecture: 'x64'
        
     - name: Install Conan
      run: pip install "conan<2.0" pytest && conan --version

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.27.x'

    - name: Cache Conan packages
      id: conan-cache
      uses: actions/cache@v2
      with:
        path: '/home/runner/.conan/*'
        key: ${{ runner.os }}${{matrix.BUILD_TYPE}}-conan
        restore-keys: ${{ runner.os }}${{matrix.BUILD_TYPE}}-conan

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.BUILD_TYPE}}
    
    - name: Install
      run: cmake --install /home/runner/work/ChitChat/ChitChat/build

    - name: Test
      working-directory: ${{github.workspace}}/build  
      run: ctest -C ${{matrix.BUILD_TYPE}} --output-on-failure
   